In [1]:
import numpy as np

In [2]:
def compute_integral_image(image, integral_image):
    """
    Compute the integral image using the provided numpy functions and ndarray methods.
    
    Args:
    - image (2D numpy array): grayscale image
    - integral_image (2D numpy array): integral image of the same size
    
    Returns:
    - integral_image (2D numpy array): integral image of the same size
    """

    # Compute cumulative sum along the rows using only allowed numpy functions
    integral_image[:, 0] = image[:, 0]
    for col in range(1, image.shape[1]):
        integral_image[:, col] = np.add(integral_image[:, col - 1], image[:, col])

    # Compute cumulative sum of the previous result along the columns
    # integral_image[0, :] = integral_image[0, :]
    for row in range(1, image.shape[0]):
        integral_image[row, :] = np.add(integral_image[row - 1, :], integral_image[row, :])
    
    return integral_image

In [3]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
integral_image = compute_integral_image(arr, np.zeros_like(arr))

print(integral_image)

[[ 1  3  6]
 [ 5 12 21]
 [12 27 45]]


In [4]:
from concrete import fhe

# Basic Example 
```python
from concrete import fhe

def add(x, y):
    return x + y

compiler = fhe.Compiler(add, {"x": "encrypted", "y": "clear"})

inputset = [(2, 3), (0, 0), (1, 6), (7, 7), (7, 1)]
circuit = compiler.compile(inputset)

x = 4
y = 4

clear_evaluation = add(x, y)
homomorphic_evaluation = circuit.encrypt_run_decrypt(x, y)

print(x, "+", y, "=", clear_evaluation, "=", homomorphic_evaluation
```

In [5]:
compiler = fhe.Compiler(compute_integral_image,
                        {"image": "encrypted", "integral_image": "encrypted"})

# Add N matrix with random values to the inputset
N = 10
pixels = 3
inputset = []
for i in range(N):
    inputset.append((np.random.randint(0, 255, size=(pixels, pixels)), 
                     np.zeros((pixels, pixels), dtype=np.int32)))

circuit = compiler.compile(inputset)

In [6]:
clear_evaluation = compute_integral_image(inputset[0][0], inputset[0][1])

homomorphic_evaluation = circuit.encrypt_run_decrypt(inputset[0][0], inputset[0][1])

print("Clear evaluation:\n", clear_evaluation)
print("Homomorphic evaluation:\n", homomorphic_evaluation)

print("Success!!" if np.array_equal(clear_evaluation, homomorphic_evaluation) else "Failure :(")

Clear evaluation:
 [[ 191  211  369]
 [ 395  643  937]
 [ 627 1038 1472]]
Homomorphic evaluation:
 [[ 191  211  369]
 [ 395  643  937]
 [ 627 1038 1472]]
Success!!
